### PR TITLE
Made some changes and tested

### PR DESCRIPTION
**Pull request by RuslanIbrahimov**
Tested Marat's Pizza web page.

### CODE REVIEW

**Review by saiyaraparhat1025 — APPROVED** [review]
nice job!

**Review by WaseemZ — APPROVED** [review]
Good Job Ruslan ! Looks good to me.

**Review by amir919 — APPROVED** [review]
great job brother

**Review by marat25 — APPROVED** [review]
Baycan, good job!

**Comment by Muradil-Erkin** [comment]
@RuslanIbrahimov Can you please make sure you only check-in the file that has your Selenium code? You now have 10 file changes.

**Comment by Muradil-Erkin** [comment]
Closing this as this will be done in a new pull request.

**Pull request closed without merging**
