### PR TITLE
HeLp! and ReViEw!

### PR DESCRIPTION
**Pull request by saiyaraparhat1025**
please take your time and review it! thank you!

### CODE REVIEW

**Review by RuslanIbrahimov — APPROVED** [review]
good job!

**Review by WaseemZ — APPROVED** [review]
Good job ! looks great to me !

**Review by amir919 — APPROVED** [review]
I have reviewed it looks good

**Review by marat25 — APPROVED** [review]
Good job! Keep smiling;)

**Review by marat25 — CHANGES_REQUESTED** [review]
You were mean, so go get your HW done!

**Review by RoseKamontip — APPROVED** [review]
look great to me :)

**Review by Nurala — APPROVED** [review]
Looks nice!

**Review by shirinayk — CHANGES_REQUESTED** [review]
You don't have the step for clicking that "Continue to check out" button

**Comment by saiyaraparhat1025** [comment]
> You don't have the step for clicking that "Continue to check out" button

ive just made a changes and requested a new pull.

**Review by Muradil-Erkin — CHANGES_REQUESTED** [review]
Can you please make sure you only check in the file that you have your selenium test code changes and leave out the rest? @saiyaraparhat1025

**Comment by Muradil-Erkin** [comment]
Closing this as this will be done in a new pull request.

**Pull request closed without merging**
