### PR TITLE
I have made some changes

### PR DESCRIPTION
**Pull request by amir919**
Tested Marats Pizza webpage please review it

### CODE REVIEW

**Review by RuslanIbrahimov — APPROVED** [review]
very good job!

**Review by saiyaraparhat1025 — APPROVED** [review]
you worked very hard! amir! you are well deserve this "approve".

**Review by WaseemZ — APPROVED** [review]
Looks great to me Amir good job !

**Review by marat25 — APPROVED** [review]
Great!

**Review by Muradil-Erkin — CHANGES_REQUESTED** [review]
@amir919 Can you please make sure you only check in the file that you have your selenium test code changes and leave out the rest?

**Comment by Muradil-Erkin** [comment]
Closing this as this will be done in a new pull request.

**Pull request closed without merging**
