### PR TITLE
Marat: HW - Amazon Cart Automation

### PR DESCRIPTION
**Pull request by marat25**
Done automation testing on Marat's Pizza order form

### CODE REVIEW

**Review by RuslanIbrahimov — APPROVED** [review]
good job dude

**Review by amir919 — APPROVED** [review]
Great job Marat/teacher

**Review by saiyaraparhat1025 — APPROVED** [review]
thanks for your good work, doctor!

**Review by WaseemZ — APPROVED** [review]
Great job teacher Lahore !

**Comment by marat25** [comment]
> thanks for your good work, doctor!

Doctor? Wth?

**Review by Muradil-Erkin — CHANGES_REQUESTED** [review]
@marat25 Can you please make sure you only check in the file that you have your selenium test code changes and leave out the rest?

**Comment by Muradil-Erkin** [comment]
Closing this as this will be done in a new pull request.

**Pull request closed without merging**
