### PR TITLE
mansoor / have made some changes

### PR DESCRIPTION
**Pull request by mansoor81**
have made some changes and tested.

### CODE REVIEW

**Review by RuslanIbrahimov — APPROVED** [review]
tested. works well!

**Review by saiyaraparhat1025 — APPROVED** [review]
lgtm

**Review by shirinayk — CHANGES_REQUESTED** [review]
Line 64, you selected credit card options but you don't have any codes for the following steps

**Review by Muradil-Erkin — CHANGES_REQUESTED** [review]
@mansoor81 Can you please make sure you only check in the file that you have your selenium test code changes and leave out the rest?

**Comment by Muradil-Erkin** [comment]
Closing this as this will be done in a new pull request.

**Pull request closed without merging**
