### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by nanfisa**
please help me review

### CODE REVIEW

**Review by shirinayk — CHANGES_REQUESTED** [review]
Line 56 & 63: if you use cssSelector, the space in your string should be replaced with " . "
Also your code for clicking that "same address" and "save info" should be before cashOrCard.

**Comment by marat25** [comment]
> Line 56 & 63: if you use cssSelector, the space in your string should be replaced with " . "
> Also your code for clicking that "same address" and "save info" should be before cashOrCard.

Agreed on that too!

**Review by marat25 — CHANGES_REQUESTED** [review]
You should make some changes on line 56, 63 and 68 where you missed "." in between the class names

**Review by Muradil-Erkin — CHANGES_REQUESTED** [review]
@nanfisa If i'm not wrong, I think you're missing some "}"s at the end of the file.

**Comment by Muradil-Erkin** [comment]
Closing this as this will be done in a new pull request.

**Pull request closed without merging**
