### PR TITLE
Shirinay: Pizza Page homework

### PR DESCRIPTION
**Pull request by shirinayk**
Please see title

### CODE REVIEW

**Review by RoseKamontip — APPROVED** [review]
Look awesome!

**Review by Nurala — APPROVED** [review]
Looks great to me!

**Review by marat25 — COMMENTED** [review]
for check boxes, i think it's better to use the same method for both. And how and where did you get to use xPath method? Could you share pls

**Comment by shirinayk** [comment]
> for check boxes, i think it's better to use the same method for both. And how and where did you get to use xPath method? Could you share pls

I don't think you have to use same methods, since using the className only returns the first web element, so the second one i could only use xpath. Teacher actually showed it in class. So i went to the element i wanna click then right click on the class then select Copy-Copy Xpath

**Comment by marat25** [comment]
> > for check boxes, i think it's better to use the same method for both. And how and where did you get to use xPath method? Could you share pls
> 
> I don't think you have to use same methods, since using the className only returns the first web element, so the second one i could only use xpath. Teacher actually showed it in class. So i went to the element i wanna click then right click on the class then select Copy-Copy Xpath

Well, XPath is very new thing for us.. How about creating a list of elements since we have more than one class with the same tagName?

**Comment by marat25** [comment]
> > for check boxes, i think it's better to use the same method for both. And how and where did you get to use xPath method? Could you share pls
> 
> I don't think you have to use same methods, since using the className only returns the first web element, so the second one i could only use xpath. Teacher actually showed it in class. So i went to the element i wanna click then right click on the class then select Copy-Copy Xpath

and there we could use a .get() method to identify those two elements

**Comment by marat25** [comment]
> > > for check boxes, i think it's better to use the same method for both. And how and where did you get to use xPath method? Could you share pls
> > 
> > 
> > I don't think you have to use same methods, since using the className only returns the first web element, so the second one i could only use xpath. Teacher actually showed it in class. So i went to the element i wanna click then right click on the class then select Copy-Copy Xpath
> 
> and there we could use a .get() method to identify those two elements

I mean if XPath works very well, then who we cares right?

**Comment by shirinayk** [comment]
> > > > for check boxes, i think it's better to use the same method for both. And how and where did you get to use xPath method? Could you share pls
> > > 
> > > 
> > > I don't think you have to use same methods, since using the className only returns the first web element, so the second one i could only use xpath. Teacher actually showed it in class. So i went to the element i wanna click then right click on the class then select Copy-Copy Xpath
> > 
> > 
> > and there we could use a .get() method to identify those two elements
> 
> I mean if XPath works very well, then who we cares right?



> > > for check boxes, i think it's better to use the same method for both. And how and where did you get to use xPath method? Could you share pls
> > 
> > 
> > I don't think you have to use same methods, since using the className only returns the first web element, so the second one i could only use xpath. Teacher actually showed it in class. So i went to the element i wanna click then right click on the class then select Copy-Copy Xpath
> 
> and there we could use a .get() method to identify those two elements

Xpath is new to me too, I watched the video again and got the xpath the way he showed in class. I couldn't make it work using list, because it keeps giving me exceptions such as " element not clickable" and "index out of bond"

**Comment by shirinayk** [comment]
> > > > for check boxes, i think it's better to use the same method for both. And how and where did you get to use xPath method? Could you share pls
> > > 
> > > 
> > > I don't think you have to use same methods, since using the className only returns the first web element, so the second one i could only use xpath. Teacher actually showed it in class. So i went to the element i wanna click then right click on the class then select Copy-Copy Xpath
> > 
> > 
> > and there we could use a .get() method to identify those two elements
> 
> I mean if XPath works very well, then who we cares right?

Yep, you're right. As long as it works, its all good lol

**Review by Muradil-Erkin — APPROVED** [review]
I think this is good work! All my requirements are met!

**Pull request merged**
