### PR TITLE
Waseem: Marat's Pizza Shop order form 

### PR DESCRIPTION
**Pull request by WaseemZ**
These are my automated testing codes for Marat's Pizza's order form checking to see if everything is working and can be filled. Please review carefully and let me know if anything should be changed before merging to the master branch. Thank you !

### CODE REVIEW

**Review by RuslanIbrahimov — APPROVED** [review]
good job

**Review by saiyaraparhat1025 — CHANGES_REQUESTED** [review]
change firstname and lastname to "sara the queen"!

**Review by saiyaraparhat1025 — APPROVED** [review]

**Review by marat25 — APPROVED** [review]
Good job

**Review by shirinayk — CHANGES_REQUESTED** [review]
Line 47 & 49 didn't work for me, did it work for you?
Also before line 51 happens, there should be some codes to click on "Credit Card" button then it should fill in the blanks

**Review by Muradil-Erkin — COMMENTED** [review]
@WaseemZ Can you please make sure you only check in the file that you have your selenium test code changes and leave out the rest?

**Comment by WaseemZ** [comment]
@shirinayk Yes lines 46 and 48 work fine for me.

**Comment by Muradil-Erkin** [comment]
Closing this as this will be done in a new pull request.

**Pull request closed without merging**
