### PR TITLE
Nurala: Made some changes

### PR DESCRIPTION
**Pull request by Nurala**
See title

### CODE REVIEW

**Review by RoseKamontip — APPROVED** [review]
LGTM :)

**Review by shirinayk — CHANGES_REQUESTED** [review]
Line 72 : you clicked on the credit card button but u didn't fill in all the required blank such as CreditCard Number and name, etc.
And also you don't have the step for clicking that "Continue to check out" button.

**Review by saiyaraparhat1025 — APPROVED** [review]
LGTM

**Review by marat25 — APPROVED** [review]
Looks great to me here, don't what Shirinay is not happy about:)))))

**Review by Muradil-Erkin — CHANGES_REQUESTED** [review]
@Nurala Can you please make sure you only check in the file that you have your selenium test code changes and leave out the rest?

**Comment by Muradil-Erkin** [comment]
Closing this as this will be done in a new pull request.

**Pull request closed without merging**
