### PR TITLE
final changes

### PR DESCRIPTION
**Pull request by saiyaraparhat1025**
made some changes and review it

### CODE REVIEW

**Review by shirinayk — APPROVED** [review]
Looks nice;)

**Review by marat25 — APPROVED** [review]
Awesome job Sara! Keep rolling

**Review by RuslanIbrahimov — APPROVED** [review]
awesome

**Review by Muradil-Erkin — CHANGES_REQUESTED** [review]
@saiyaraparhat1025 Can you please make sure you only check in the file that you have your selenium test code changes and leave out the rest?

**Comment by Muradil-Erkin** [comment]
Closing this as this will be done in a new pull request. @saiyaraparhat1025

**Pull request closed without merging**
